services:
  - type: web
    name: the-mall-cafe
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: HOSTNAME
        value: 0.0.0.0
